### ISSUE TITLE
Should not scroll <body> when mouse inside sidecar

### ISSUE THREAD

**Issue by rnons** [gitterHQ/sidecar#36]
See http://24pullrequests.com/ for example, click `open chat`, scroll down in sidecar, body got scrolled down.

I assume this can be fixed by listening to `mouseover` and `mouseout` events, then toggle `overflow: hidden` on the `<body>` element

**Comment by MadLittleMods** [comment]
@rnons You can disable this if you want, just listen to the mousewheel events after mousing over the Sidecar target and `e.preventDefault()`.

I would prefer to leave it as is because it doesn't intrude on the pages normal functionality. This is how scrollbars work in browsers: https://jsfiddle.net/7kt821k4/1/

**Comment by rnons** [comment]
I see, I made a jsfiddle as you suggest: https://jsfiddle.net/g1wx4puj/2/, though it doesn't seem to work as expected in Firefox.

Wouldn't it be easier to add the `wheel` event listener and `e.preventDefault()` in `dist/sidecar.v1.js`?

**Comment by MadLittleMods** [comment]
It would be easier for you but would require a new option to be added to the Sidecar option surface area and clutter the API with something that can be done outside and is a bit intrusive.
